name: Build v2 for PR

on:
  pull_request:
    branches: [ v2 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo

    - name: Set up JDK 17 (LTS)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn install --file pom.xml

    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: ChatItem.jar
        path: target/ChatItem-*.jar