name: Build v2

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo

    - name: Set up JDK 17 (LTS)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn install --file pom.xml

    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: ChatItem.jar
        path: target/ChatItem-*.jar
    - name: Send file README.md to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: target/ChatItem-*.jar
